version: "3.9"
services:
  app_database:
    container_name: springboot-postgresql
    image: srdjanmaric/springboot-postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/helloworld
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  web_external_api:
    container_name: external_api
    image: srdjanmaric/external_api
    ports:
      - "8081:8080"
  postgresqldb:
    container_name: postgresql_db
    image: srdjanmaric/postgres
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=eagle
      - POSTGRES_USER=postgres
      - POSTGRES_DB=helloworld
  nginx:
    container_name: nginx
    image: srdjanmaric/nginx:1.14.2
    depends_on:
      - app_database
      - web_external_api
      - postgresqldb
    ports:
      - "80:80"
